id: 3c223f95a72446f989519e881d25f3b9
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_543-The_Root_Manual_of_the_Rites_of_Manjusri-v2
  language: bo
  author: ''
  volume: {}
